### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by cthart** [MadSpindel/swish-python#15]
Implementing Swish payments, I note that several APIs now have v2 versions, while this code assumes all APIs are on the v1 endpoint.

**Comment by MadSpindel** [comment]
No, I'm not using it anymore but if you want to make it compatible with v2 I would gladly accept it.

**Comment by cthart** [comment]
Could you apply the outstanding pull requests? One adds a field to one of the models that also needs to be added to the other. I can submit a proper pull request for that if you need it.

**Comment by MadSpindel** [comment]
I've sent you an invite as maintainer. Feel free to add the PRs you believe is needed.

**Comment by cthart** [comment]
I had a PyPI account but I lost access to it when I upgraded iPhones and my Google Authenticator data didn't come across to my new phone (guess who upgraded to Authy after that?)

It is possible to regain access, I'll give it a go again (I tried before but they wanted an email from my alternate email address, which back then was just an alias on my Gmail. Now it's hosted elsewhere I can do that). I'll update this issue when I get access again.

I have more changes queued -- the Swish environments are now called Production, MSS, and Sandbox. I'm making Test an alias for MSS, but with a note that it's deprecated.

**Comment by cthart** [comment]
I made the release here on GitHub, so it would be great if you @MadSpindel could push it to PyPI.

**Comment by MadSpindel** [comment]
@cthart Cool, I think we should try to use GitHub Actions to publish to PyPi. I've added a workflow, but I think it will only run on the next release, not the one you created. Should we remove your release and try again?

**Comment by cthart** [comment]
I deleted the release and recreated it but the workflow didn't run. Feel free to try it.

**Comment by MadSpindel** [comment]
OK, I'll see if I can find the reason for that.

**Comment by MadSpindel** [comment]
It worked when I did a test release now...

https://pypi.org/project/swish/ 1.2 version is available on PyPi.

**Comment by cthart** [comment]
Closing this issue. Will contact @MadSpindel privately if/when I get my PyPI access restored (or give up and create a new account...)
