### ISSUE TITLE
Python 2 and non-ascii characters in the message

### ISSUE THREAD

**Issue by davidparsson** [MadSpindel/swish-python#8]
I've been trying to create payments where the message contains Swedish characters (åäö) in a Python 2 project. When I got the callback, Python failed to parse the message.

Wouldn't it be reasonable to encode the data as UTF-8, and add the appropriate headers? I haven't tried it myself, but I assume that doing so should resolve this issue.

**Comment by cthart** [comment]
Do we really still need to keep supporting Python 2?

**Comment by davidparsson** [comment]
Nope, not from my perspective. I'll close this.
